export Avatar from './components/Avatar';
export FormItemSort from './components/FormItemSort';
export InputPrice from './components/InputPrice';
export Upload from './components/Upload';
export FormItemUpload from './components/FormItemUpload';
export TableImage from './components/TableImage';
export TableImages from './components/TableImages';
export Select from './components/Select';
export TreeSelect from './components/TreeSelect';
